// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbolalijksjixmhzlljf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZib2xhbGlqa3NqaXhtaHpsbGpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMjMwMzQsImV4cCI6MjA2Njg5OTAzNH0.F2eSDBPJ_rhj-Ww0qeM1Vha7Sjy4HZhq42VC7WuMVwc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});